site_name: Andres Ariza's blog
site_description: Andres Ariza's blog
site_url: https://aarizat.github.io
site_author: Andres Ariza-Triana
copyright: Copyright &copy; 2023 Andres Ariza-Triana

theme:
  name: material
  locale: en
  features:
    - navigation.sections
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

nav:
  - About: about.md
  - Home: index.md

plugins:
  - search
  - roamlinks
  - blogging:
      meta_time_format: "%Y-%m-%d %H:%M:%S"
      time_format: '%Y-%m-%d %H:%M:%S'
      dirs:
        - posts

# Extensions
markdown_extensions:
  - def_list
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aarizatr
    - icon: fontawesome/brands/github
      link: https://github.com/aarizat
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aarizatr/
    - icon: fontawesome/solid/envelope
      link: mailto:aarizatr@gmail.com
  analytics:
    provider: google
    property: G-KG3LCD6FSH