site_name: Andres Ariza-Triana
site_description: Andres Ariza's blog
site_url: https://aarizat.github.io
site_author: Andres Ariza-Triana
copyright: Copyright &copy; 2023 Andres Ariza-Triana

theme:
  name: material
  locale: en
  custom_dir: overrides
  favicon: images/favicon.ico
  logo: images/favicon.ico
  features:
    - navigation.sections
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

plugins:
  - meta
  - search
  - tags
  - blog:
      blog_dir: .
  - rss:
      match_path: blog/posts/.*
      comments_path: "#__comments"
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Blog:
      - index.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aarizatr
    - icon: fontawesome/brands/github
      link: https://github.com/aarizat
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aarizatr/
    - icon: fontawesome/solid/envelope
      link: mailto:aarizatr@gmail.com
  analytics:
    provider: google
    property: G-KG3LCD6FSH