name: My Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Display system information
      run: |
        uname -a
        sw_vers
    - name: Check Python version
      run: python --version
    - name: Setup Pyenv
      run: |
        curl https://pyenv.run | bash
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.bash_profile
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $HOME/.bash_profile
        echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init --path)"\nfi' >> $HOME/.bash_profile
        source $HOME/.bash_profile
        eval "$(pyenv init -)"
    - name: Install Python 3.8.2 with Pyenv
      run: |
        pyenv install 3.8.2
        pyenv global 3.8.2
    - name: Check Python versions installed with Pyenv
      run: pyenv versions
